=== VijayEluri/honeycomb/hctest/dtf/tests/ut/dtf.dtd
<!ENTITY % aggregations "for|sequence|parallel|try|timer|distribute|parallelloop|result|if|fail|sleep|log">
<!ENTITY % functions "function|call">
<!ENTITY % events "record|event|query|nextresult|stats|graph">
<!ENTITY % components "local|component">
<!ENTITY % local_commands "loadproperties|createstorage|lockcomponent|unlockcomponent|property|import|createrange|cat">
<!ENTITY % component_commands "sleep|echo|event|fail|getfile|stopcomponent|loop|fetchresult|attribute">
<!ENTITY % test_commands "testsuite|testscript">

<!ENTITY % conditions "and|eq|gt|lt|neq|or|within">

<!ENTITY % dtf_tags "%aggregations;|%components;|%test_commands;|%events;|%functions;"> 

<!ELEMENT script ( info, (%dtf_tags;)* )>
<!ATTLIST script
          name        CDATA #REQUIRED>

<!ELEMENT info ( author,description ) >

<!ELEMENT author ( name, email )>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT function (param*,(%dtf_tags;)*)>
<!ATTLIST function
          name CDATA #REQUIRED>

<!ELEMENT param EMPTY>
<!ATTLIST param 
          name CDATA #REQUIRED
          type (optional|required) "optional">

<!ELEMENT call (property)*>
<!ATTLIST call
          function CDATA #REQUIRED>
          
<!ELEMENT import EMPTY>
<!ATTLIST import
          uri 		 CDATA #REQUIRED
          loadFuncs  CDATA "true"
          loadRefs   CDATA "true">
  
<!ELEMENT testsuite ANY>
<!ATTLIST testsuite
          name   			CDATA #REQUIRED
          continueOnFailure CDATA #IMPLIED> 

<!ELEMENT testscript (testproperty)*>
<!ATTLIST testscript
          uri  CDATA #REQUIRED>

<!ELEMENT testproperty EMPTY>
<!ATTLIST testproperty
          name  CDATA #REQUIRED
          value CDATA #REQUIRED>

<!ELEMENT timer (%dtf_tags;|%component_commands;)*>
<!ATTLIST timer
          interval CDATA #REQUIRED
          property CDATA #IMPLIED>

<!ELEMENT sequence (%dtf_tags;)*>

<!ELEMENT parallel (%dtf_tags;)*>

<!ELEMENT local (%local_commands;|%component_commands; | attribute)*>

<!ELEMENT component (%component_commands; | event | attribute)*>
<!ATTLIST component
          id        CDATA #REQUIRED>

<!ELEMENT loadproperties EMPTY>
<!ATTLIST loadproperties
          uri          CDATA #REQUIRED
          overwrite    CDATA #IMPLIED>

<!ELEMENT cat (#PCDATA)>
<!ATTLIST cat
          uri     CDATA #REQUIRED
          append  CDATA "true"
          trim    CDATA "true">
          
<!ELEMENT log (#PCDATA)>
<!ATTLIST log 
          tag   CDATA "log"
          level CDATA "info">
          
<!ELEMENT echo (#PCDATA)>
<!ATTLIST echo
          message CDATA #IMPLIED>

<!ELEMENT lockcomponent (attrib)*>
<!ATTLIST lockcomponent
          id      CDATA #REQUIRED
          name    CDATA #IMPLIED
          timeout CDATA "60s">

<!ELEMENT attrib EMPTY>
<!ATTLIST attrib
          name  CDATA #IMPLIED
          value CDATA #IMPLIED>

<!ELEMENT unlockcomponent EMPTY>
<!ATTLIST unlockcomponent 
          id CDATA #REQUIRED>

<!ELEMENT stopcomponent EMPTY>

<!ELEMENT createstorage EMPTY>
<!ATTLIST createstorage
          id   CDATA #REQUIRED
          path CDATA #REQUIRED>
          
<!ELEMENT createrange EMPTY>
<!ATTLIST createrange
          name    CDATA #REQUIRED
          value   CDATA #REQUIRED
          recycle CDATA #IMPLIED>
          
<!-- moving files to/from components tags -->

<!ELEMENT putfile EMPTY>
<!ATTLIST putfile
		  uri        CDATA #REQUIRED
		  remotefile CDATA #REQUIRED>

<!ELEMENT getfile EMPTY>
<!ATTLIST getfile
		  uri        CDATA #REQUIRED
		  remotefile CDATA #REQUIRED>

<!-- flow control tags -->
          
<!ELEMENT try ((%dtf_tags;),catch*,finally?)>
<!ELEMENT catch (%dtf_tags;)>
<!ATTLIST catch
          exception CDATA #IMPLIED
          property  CDATA #IMPLIED>
<!ELEMENT finally (%dtf_tags;)>

<!ELEMENT fail EMPTY>
<!ATTLIST fail
          message    CDATA #REQUIRED>

<!ELEMENT for (%dtf_tags;)*>
<!ATTLIST for 
          property CDATA #REQUIRED
          range    CDATA #REQUIRED>

<!ELEMENT distribute (%dtf_tags;)>
<!ATTLIST distribute
          func 			CDATA #IMPLIED
          duration 		CDATA #IMPLIED
          iterations 	CDATA #IMPLIED
          timer 		CDATA #IMPLIED
          unit 			CDATA "1s"
          property 		CDATA #IMPLIED
          workers 		CDATA #REQUIRED
          id            CDATA #IMPLIED>

<!ELEMENT parallelloop (%dtf_tags;)>
<!ATTLIST parallelloop
          range CDATA #IMPLIED
          property CDATA #IMPLIED>

<!ELEMENT loop (loop|%component_commands;)*>
<!ATTLIST loop
          range 	CDATA #IMPLIED
          property 	CDATA #IMPLIED
          type		CDATA "sequence">

<!ELEMENT fetchresult EMPTY>
<!ATTLIST fetchresult
          cursor    CDATA #REQUIRED
          recycle   CDATA #IMPLIED
          fetchsize CDATA #IMPLIED>
          
<!ELEMENT sleep EMPTY>
<!ATTLIST sleep 
          time CDATA #REQUIRED>

<!ELEMENT result ANY>
<!ATTLIST result
          uri    CDATA	#IMPLIED
          type   CDATA	"xml">

<!ELEMENT record (attribute*,(%dtf_tags;)*)>
<!ATTLIST record
          uri    CDATA #IMPLIED
          type   CDATA #REQUIRED
          event  CDATA #IMPLIED
          append CDATA #IMPLIED
          refid  CDATA #IMPLIED>

<!ELEMENT event ANY>
<!ATTLIST event 
          name  CDATA #IMPLIED
          id    CDATA #IMPLIED
          refid CDATA #IMPLIED>
          
<!ELEMENT stats  EMPTY>
<!ATTLIST stats 
          cursor CDATA #REQUIRED
          event  CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
          name      CDATA #REQUIRED
          value     CDATA #REQUIRED
          overwrite CDATA #IMPLIED>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
          name  CDATA #REQUIRED
          value CDATA #REQUIRED
          type  CDATA "string"
          index CDATA #IMPLIED
          length CDATA "64">

<!ELEMENT nextresult EMPTY>
<!ATTLIST nextresult
          cursor  CDATA #REQUIRED
          recycle CDATA #IMPLIED>

<!ELEMENT query (select?,where?) >
<!ATTLIST query 
          uri    CDATA	#REQUIRED
          type   CDATA  "database"
          event  CDATA  #REQUIRED
          cursor CDATA 	#REQUIRED> 

<!ELEMENT select (field)*>

<!ELEMENT field EMPTY>
<!ATTLIST field 
          name CDATA #REQUIRED
          type CDATA #IMPLIED>

<!ELEMENT where (%conditions;)>

<!ELEMENT and (%conditions;)*>
<!ELEMENT or (%conditions;)*>

<!ELEMENT gt EMPTY>
<!ATTLIST gt 
          op1	    CDATA #REQUIRED
          op2		CDATA #REQUIRED
          type  	CDATA "string"
          nullable  CDATA "false">

<!ELEMENT lt EMPTY>
<!ATTLIST lt 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">

<!ELEMENT eq EMPTY>
<!ATTLIST eq 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">

<!ELEMENT neq EMPTY>
<!ATTLIST neq 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">
          
<!ELEMENT within EMPTY>
<!ATTLIST within
          op1       CDATA #REQUIRED
          op2       CDATA #REQUIRED
          tolerance CDATA #REQUIRED>

<!ELEMENT if ((%conditions;),then,else?) >

<!ELEMENT then (%dtf_tags;)* >
<!ELEMENT else (%dtf_tags;)* >

<!ELEMENT graph (series)*>
<!ATTLIST graph
          uri    CDATA #IMPLIED
          type   CDATA #REQUIRED
          title  CDATA #REQUIRED
          width  CDATA #IMPLIED
          height CDATA #IMPLIED>

<!ELEMENT series EMPTY>
<!ATTLIST series
		  name        CDATA #REQUIRED
          cursor      CDATA #REQUIRED
          separateby  CDATA #IMPLIED
          aggregateby CDATA #IMPLIED
          aggfunc     CDATA "average"
          lowerlimit  CDATA #IMPLIED
          upperlimit  CDATA #IMPLIED
          mode        CDATA #IMPLIED
          sampleunit  CDATA "1s">
<!-- Internal DTF Elements -->
<!-- add elements as necessary to get more information out of the 
     toString on the Action classes -->

<!ELEMENT nodeinfo EMPTY>
<!ATTLIST nodeinfo 
          id   		CDATA #REQUIRED>

<!ELEMENT lock EMPTY>
<!ATTLIST lock 
          id   		CDATA #REQUIRED>

<!ELEMENT unlock EMPTY>
<!ATTLIST unlock 
          id    CDATA #REQUIRED
          owner CDATA #IMPLIED>
          
<!ELEMENT connect EMPTY>
<!ATTLIST connect
          id    CDATA #REQUIRED>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/storage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="storage">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>Unit test for the storage tag.</description>
    </info>
   
   	<local> 
  		<echo>Create a bunch of storages.</echo>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        <loadproperties uri="storage://INPUT/ut.properties"/>
  	</local>
  	<for range="[1..10]" property="id">
        <local>	
            <createstorage id="STORAGE${id}" path="${dtf.xml.path}/output/STORE${id}"/>
        </local>
    </for>
   
   	<try> 
        <local>
            <createstorage id="STORAGE5" path="${dtf.xml.path}/output"/>
        </local>
        <catch exception="${dtf.StorageException}" property="message">
        	<local>
        		<echo>Caught correction exception: ${message}</echo>
        	</local>
        </catch>
    </try>
    
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/perf/parallelloop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="distribute">
	<info>
		<author>
			<name>Rodney Gomes</name>
			<email>rodney.gomes@sun.com</email>
		</author>
		<description>DTF distribute performance test.</description>
	</info>

	<local>
		<createstorage id="INPUT" path="${dtf.xml.path}/input" />
		<createstorage id="OUTPUT" path="${dtf.xml.path}/output" />
		<loadproperties uri="storage://INPUT/test.properties" />
	</local>

	<record type="txt" uri="storage://OUTPUT/perf1.txt" append="false">
		<for property="iter" range="[1..20000]">
			<sequence>
				<event name="dtf.echo">
					<attribute name="prop1" value="${iter}" />
				</event>
			</sequence>
		</for>
	</record>

	<record type="txt" uri="storage://OUTPUT/perf2.txt" append="false">
		<parallelloop property="agent" range="${agent.ids}">
			<for property="iter" range="[1..20000]">
				<sequence>
					<event name="dtf.echo">
						<attribute name="prop1" value="${iter}" />
					</event>
				</sequence>
			</for>
		</parallelloop>
	</record>

	<query uri="storage://OUTPUT/perf1.txt" 
	       type="txt" 
	       event="dtf.echo"
	       cursor="cursor" />

	<record type="object" uri="property://dbperf">
		<stats cursor="cursor" event="stats" />
	</record>
	
	<local>
		<echo>
			For Loop Performance
			Events per second: ${dbperf.avg_occ} 
			Total of Events:   ${dbperf.tot_occ} 
			Total Duration:    ${dbperf.tot_dur}s
		</echo>
	</local>
	
	<query uri="storage://OUTPUT/perf2.txt" 
           type="txt" 
           event="dtf.echo"
           cursor="cursor"/>
           
    <record type="object" uri="property://dbperf"> 
   		<stats cursor="cursor" event="stats"/>
    </record> 
    
    <local>
   		<echo>
              Parallelloop of For loop
              Events per second: ${dbperf.avg_occ}
              Total of Events:   ${dbperf.tot_occ}
              Total Duration:    ${dbperf.tot_dur}s
        </echo> 
    </local>	
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/limits/recorder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="recorder_perf">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>DTF recorder limits test.</description>
    </info>
    
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>

        <echo>Recorder Limits Tests</echo>
    </local>

    <local>
        <echo>Generating data...</echo>
        <property name="prop1" value="222222"/>
        <property name="prop2" value="abababababababababababababababa"/>
        <property name="iterations" value="20000"/>
    </local> 
    
	<record type="txt" 
            uri="storage://OUTPUT/recorder1.txt"
            append="false"> 
        <for property="iteration" range="1..${iterations}">
            <event name="dtf.event">
                <attribute name="value1" value="${iteration}"/>
                <attribute name="value2" value="${prop1}"/>
                <attribute name="value3" value="${prop2}"/>
                <attribute name="value4" value="${iteration}-${prop1}"/>
                <attribute name="value5" value="${prop1}${prop1}"/>
                <attribute name="value6" value="${prop2}${prop2}"/>
                <attribute name="value7" value="${prop2}${prop2}${prop1}"/>
                <attribute name="value8" value="${prop2}${prop2}${prop1}"/>
                <attribute name="value9" value="${prop2}${prop2}${prop1}"/>
            </event>
        </for>
    </record>
    
    <query type="txt" 
           uri="storage://OUTPUT/recorder1.txt" 
           event="dtf.event"
           cursor="cursor"/>
           
    <record type="object" uri="property://perf"> 
    	<stats cursor="cursor" event="stats"/>
    </record> 
    <local>
   		<echo>
              TXT Recorder Performance Stats 
              -----------------------------------
              Events per second: ${perf.avg_occ}
              Total of Events:   ${perf.tot_occ}
              Total Duration:    ${perf.tot_dur}s
        </echo> 
    </local>
    
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/testsuite-sub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="testsuite-sub">
	<info>
		<author>
			<name>Rodney Gomes</name>
			<email>rodney.gomes@sun.com</email>
		</author>
		<description>sub test suite used by test suite unit test.</description>
	</info>

	<local>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>
        <createstorage id="INPUT" path="${dtf.xml.path}"/>
	</local>
	
	<testsuite name="testsuite2" continueOnFailure="true">
		<property name="testcase.name" value="testcase-sub1"/>
		<testscript uri="storage://INPUT/testcase.xml"/>		

		<property name="testcase.name" value="testcase-sub2"/>
		<testscript uri="storage://INPUT/testcase.xml"/>		
		
		<property name="testcase.name" value="testcase-sub3"/>
		<testscript uri="storage://INPUT/testcase.xml"/>		
	</testsuite>
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/parallel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="parallel">
	<info>
		<author>
			<name>Rodney Gomes</name>
			<email>rodney.gomes@sun.com</email>
		</author>
		<description>DTF parallel unit test.</description>
	</info>

	<parallel>
		<for property="j" range="[1..4]">
			<local>
				<echo>Echo ${j}</echo>
			</local>
		</for>
		<for property="j" range="[5,6]">
			<local>
				<echo>Echo ${j}</echo>
			</local>
		</for>
		<for property="j" range="[7,8,9,10]">
			<local>
				<echo>Echo ${j}</echo>
			</local>
		</for>
	</parallel>

	<local>
		<lockcomponent id="DTFA1">
			<attrib name="type" value="dtfa"/>
		</lockcomponent>
	</local>

	<local>
		<echo>Echoing some values on the previously locked agent.</echo>
	</local>

	<parallel>
		<component id="DTFA1">
			<echo>Echo a</echo>
		</component>
		<component id="DTFA1">
			<echo>Echo b</echo>
		</component>
		<component id="DTFA1">
			<echo>Echo c</echo>
		</component>
		<component id="DTFA1">
			<echo>Echo d</echo>
		</component>
		<component id="DTFA1">
			<echo>Echo e</echo>
		</component>
		<component id="DTFA1">
			<echo>Echo f</echo>
		</component>
	</parallel>

	<component id="DTFA1">
		<echo>Echo a</echo>
		<echo>Echo b</echo>
		<echo>Echo c</echo>
		<echo>Echo d</echo>
		<echo>Echo e</echo>
		<echo>Echo f</echo>
	</component>
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/testsuite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="testsuite">
	<info>
		<author>
			<name>Rodney Gomes</name>
			<email>rodney.gomes@sun.com</email>
		</author>
		<description>Unit test for the testsuite tag.</description>
	</info>
	
	<local>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>
        <createstorage id="INPUT" path="${dtf.xml.path}"/>
	</local>

	<result uri="storage://OUTPUT/testsuite_results.xml"
	        type="xml">
    	<testsuite name="testsuite1" continueOnFailure="true">
    		<property name="testcase.name" value="testcase1"/>
    		<testscript uri="storage://INPUT/testcase.xml"/>		
            
    		<property name="testcase.name" value="testcase2"/>
    		<testscript uri="storage://INPUT/testcase.xml"/>		
            		
    		<property name="testcase.name" value="testcase3"/>
    		<testscript uri="storage://INPUT/testcase.xml"/>
    				
    		<testscript uri="storage://INPUT/testsuite-sub.xml"/>
    	</testsuite>
    </result>
    
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/functions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="component">
    <info>
         <author>
             <name>Rodney Gomes</name>
             <email>rodney.gomes@sun.com</email>
         </author> 
         <description>
             Test the basic functionality of the function/call tag which is used 
             to create functions and being able to call them from various points
             in the code.
         </description>
    </info>
    
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>
        <createstorage id="TESTINPUT" path="${dtf.xml.path}"/>
       
        <loadproperties uri="storage://INPUT/ut.properties"/>
        
        <property name="nomore" value="false"/>
	   
	    <import uri="storage://TESTINPUT/util.xml"/>
    </local>
    
    <function name="func1">
    	<param name="function" type="required"/>
    	<param name="nomore" type="optional"/>
    	
    	<local><echo>In func1</echo></local>
    	<if> 
    		<eq op1="${nomore}" op2="true"/>
    		<then>
    			<local><echo>No More.</echo></local>
    		</then>	
    		<else>	
		   		<call function="${function}"/> 
    		</else>	
    	</if>
    </function>
    
    <function name="func2">
    	<local><echo>In func2</echo></local>
    	<call function="func1">
    		<property name="nomore" value="true"/>
    	</call>
    </function>
    
    <function name="func3">
    	<local><echo>In func3</echo></local>
    	<call function="func1">
    		<property name="nomore" value="true"/>
    	</call>
    </function>

    <function name="func_event">
    	<param name="iteration" type="required"/>
    	<event name="func.event">
    		<attribute name="iteration" value="${iteration}"/>	
    	</event>
    </function>
    
    <local>
    	<echo>Recursive function calling.</echo>
    </local> 
    <call function="func1">
   		<property name="function" value="func2"/> 
    </call>

    <call function="func1">
   		<property name="function" value="func3"/> 
    </call>
    
    <local>
    	<echo>Inexistent function calling.</echo>
    </local> 
    <try>
    	<sequence>
            <call function="funcXXXX">
           		<property name="function" value="func2"/> 
            </call>
      		<fail message="Previous function called should have failed."/>
      	</sequence>
       	<catch exception="${dtf.FunctionException}" property="message">
       		<local>
       			<echo>Caught exception correctly [${message}]</echo>
       		</local>
       	</catch> 
    </try>
    
    <local>
    	<echo>Parallel stress function calling.</echo>
    </local> 
    
    <record type="txt" uri="storage://OUTPUT/function_events.txt">
   		<distribute workers="5" iterations="1000" property="iteration">
		   <call function="func_event">
                <property name="iteration" value="${iteration}"/>
           </call>
   		</distribute>
    </record>
   
    <call function="checkRecordCount">    
    	<property name="recorder.location" value="storage://OUTPUT/function_events.txt"/>	
    	<property name="recorder.type" value="txt"/>	
    	<property name="event.name" value="func.event"/>
    	<property name="record.count" value="1000"/>
   	</call>
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/loadproperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="loadproperties">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>DTF loadproperties unit test.</description>
    </info>
    
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        
        <loadproperties uri="storage://INPUT/ut.properties"/>
        <echo>The previous loadproperties should succeed.</echo>
        <echo>dtf.test.property1 = ${dtf.test.property1}</echo>
    </local>
  
    <try>
        <sequence>
            <local>
                <loadproperties uri="storage://INEXISTENT/ut.properties"/>
                <echo>*** This line should never be printed ***</echo>
            </local>
        </sequence>
        <catch exception="${dtf.StorageException}">
            <sequence>
                <local>
                    <echo>The previous loadproperties has failed correctly.</echo>
                </local>
            </sequence>
        </catch>
    </try>
    
</script>
