=== VijayEluri/honeycomb/hctest/dtf/tests/ut/dtf.dtd
<!ENTITY % aggregations "for|sequence|parallel|try|timer|distribute|parallelloop|result|if|fail|sleep|log">
<!ENTITY % functions "function|call">
<!ENTITY % events "record|event|query|nextresult|stats|graph">
<!ENTITY % components "local|component">
<!ENTITY % local_commands "loadproperties|createstorage|lockcomponent|unlockcomponent|property|import|createrange|cat">
<!ENTITY % component_commands "sleep|echo|event|fail|getfile|stopcomponent|loop|fetchresult|attribute">
<!ENTITY % test_commands "testsuite|testscript">

<!ENTITY % conditions "and|eq|gt|lt|neq|or|within">

<!ENTITY % dtf_tags "%aggregations;|%components;|%test_commands;|%events;|%functions;"> 

<!ELEMENT script ( info, (%dtf_tags;)* )>
<!ATTLIST script
          name        CDATA #REQUIRED>

<!ELEMENT info ( author,description ) >

<!ELEMENT author ( name, email )>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT function (param*,(%dtf_tags;)*)>
<!ATTLIST function
          name CDATA #REQUIRED>

<!ELEMENT param EMPTY>
<!ATTLIST param 
          name CDATA #REQUIRED
          type (optional|required) "optional">

<!ELEMENT call (property)*>
<!ATTLIST call
          function CDATA #REQUIRED>
          
<!ELEMENT import EMPTY>
<!ATTLIST import
          uri 		 CDATA #REQUIRED
          loadFuncs  CDATA "true"
          loadRefs   CDATA "true">
  
<!ELEMENT testsuite ANY>
<!ATTLIST testsuite
          name   			CDATA #REQUIRED
          continueOnFailure CDATA #IMPLIED> 

<!ELEMENT testscript (testproperty)*>
<!ATTLIST testscript
          uri  CDATA #REQUIRED>

<!ELEMENT testproperty EMPTY>
<!ATTLIST testproperty
          name  CDATA #REQUIRED
          value CDATA #REQUIRED>

<!ELEMENT timer (%dtf_tags;|%component_commands;)*>
<!ATTLIST timer
          interval CDATA #REQUIRED
          property CDATA #IMPLIED>

<!ELEMENT sequence (%dtf_tags;)*>

<!ELEMENT parallel (%dtf_tags;)*>

<!ELEMENT local (%local_commands;|%component_commands; | attribute)*>

<!ELEMENT component (%component_commands; | event | attribute)*>
<!ATTLIST component
          id        CDATA #REQUIRED>

<!ELEMENT loadproperties EMPTY>
<!ATTLIST loadproperties
          uri          CDATA #REQUIRED
          overwrite    CDATA #IMPLIED>

<!ELEMENT cat (#PCDATA)>
<!ATTLIST cat
          uri     CDATA #REQUIRED
          append  CDATA "true"
          trim    CDATA "true">
          
<!ELEMENT log (#PCDATA)>
<!ATTLIST log 
          tag   CDATA "log"
          level CDATA "info">
          
<!ELEMENT echo (#PCDATA)>
<!ATTLIST echo
          message CDATA #IMPLIED>

<!ELEMENT lockcomponent (attrib)*>
<!ATTLIST lockcomponent
          id      CDATA #REQUIRED
          name    CDATA #IMPLIED
          timeout CDATA "60s">

<!ELEMENT attrib EMPTY>
<!ATTLIST attrib
          name  CDATA #IMPLIED
          value CDATA #IMPLIED>

<!ELEMENT unlockcomponent EMPTY>
<!ATTLIST unlockcomponent 
          id CDATA #REQUIRED>

<!ELEMENT stopcomponent EMPTY>

<!ELEMENT createstorage EMPTY>
<!ATTLIST createstorage
          id   CDATA #REQUIRED
          path CDATA #REQUIRED>
          
<!ELEMENT createrange EMPTY>
<!ATTLIST createrange
          name    CDATA #REQUIRED
          value   CDATA #REQUIRED
          recycle CDATA #IMPLIED>
          
<!-- moving files to/from components tags -->

<!ELEMENT putfile EMPTY>
<!ATTLIST putfile
		  uri        CDATA #REQUIRED
		  remotefile CDATA #REQUIRED>

<!ELEMENT getfile EMPTY>
<!ATTLIST getfile
		  uri        CDATA #REQUIRED
		  remotefile CDATA #REQUIRED>

<!-- flow control tags -->
          
<!ELEMENT try ((%dtf_tags;),catch*,finally?)>
<!ELEMENT catch (%dtf_tags;)>
<!ATTLIST catch
          exception CDATA #IMPLIED
          property  CDATA #IMPLIED>
<!ELEMENT finally (%dtf_tags;)>

<!ELEMENT fail EMPTY>
<!ATTLIST fail
          message    CDATA #REQUIRED>

<!ELEMENT for (%dtf_tags;)*>
<!ATTLIST for 
          property CDATA #REQUIRED
          range    CDATA #REQUIRED>

<!ELEMENT distribute (%dtf_tags;)>
<!ATTLIST distribute
          func 			CDATA #IMPLIED
          duration 		CDATA #IMPLIED
          iterations 	CDATA #IMPLIED
          timer 		CDATA #IMPLIED
          unit 			CDATA "1s"
          property 		CDATA #IMPLIED
          workers 		CDATA #REQUIRED
          id            CDATA #IMPLIED>

<!ELEMENT parallelloop (%dtf_tags;)>
<!ATTLIST parallelloop
          range CDATA #IMPLIED
          property CDATA #IMPLIED>

<!ELEMENT loop (loop|%component_commands;)*>
<!ATTLIST loop
          range 	CDATA #IMPLIED
          property 	CDATA #IMPLIED
          type		CDATA "sequence">

<!ELEMENT fetchresult EMPTY>
<!ATTLIST fetchresult
          cursor    CDATA #REQUIRED
          recycle   CDATA #IMPLIED
          fetchsize CDATA #IMPLIED>
          
<!ELEMENT sleep EMPTY>
<!ATTLIST sleep 
          time CDATA #REQUIRED>

<!ELEMENT result ANY>
<!ATTLIST result
          uri    CDATA	#IMPLIED
          type   CDATA	"xml">

<!ELEMENT record (attribute*,(%dtf_tags;)*)>
<!ATTLIST record
          uri    CDATA #IMPLIED
          type   CDATA #REQUIRED
          event  CDATA #IMPLIED
          append CDATA #IMPLIED
          refid  CDATA #IMPLIED>

<!ELEMENT event ANY>
<!ATTLIST event 
          name  CDATA #IMPLIED
          id    CDATA #IMPLIED
          refid CDATA #IMPLIED>
          
<!ELEMENT stats  EMPTY>
<!ATTLIST stats 
          cursor CDATA #REQUIRED
          event  CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
          name      CDATA #REQUIRED
          value     CDATA #REQUIRED
          overwrite CDATA #IMPLIED>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
          name  CDATA #REQUIRED
          value CDATA #REQUIRED
          type  CDATA "string"
          index CDATA #IMPLIED
          length CDATA "64">

<!ELEMENT nextresult EMPTY>
<!ATTLIST nextresult
          cursor  CDATA #REQUIRED
          recycle CDATA #IMPLIED>

<!ELEMENT query (select?,where?) >
<!ATTLIST query 
          uri    CDATA	#REQUIRED
          type   CDATA  "database"
          event  CDATA  #REQUIRED
          cursor CDATA 	#REQUIRED> 

<!ELEMENT select (field)*>

<!ELEMENT field EMPTY>
<!ATTLIST field 
          name CDATA #REQUIRED
          type CDATA #IMPLIED>

<!ELEMENT where (%conditions;)>

<!ELEMENT and (%conditions;)*>
<!ELEMENT or (%conditions;)*>

<!ELEMENT gt EMPTY>
<!ATTLIST gt 
          op1	    CDATA #REQUIRED
          op2		CDATA #REQUIRED
          type  	CDATA "string"
          nullable  CDATA "false">

<!ELEMENT lt EMPTY>
<!ATTLIST lt 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">

<!ELEMENT eq EMPTY>
<!ATTLIST eq 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">

<!ELEMENT neq EMPTY>
<!ATTLIST neq 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">
          
<!ELEMENT within EMPTY>
<!ATTLIST within
          op1       CDATA #REQUIRED
          op2       CDATA #REQUIRED
          tolerance CDATA #REQUIRED>

<!ELEMENT if ((%conditions;),then,else?) >

<!ELEMENT then (%dtf_tags;)* >
<!ELEMENT else (%dtf_tags;)* >

<!ELEMENT graph (series)*>
<!ATTLIST graph
          uri    CDATA #IMPLIED
          type   CDATA #REQUIRED
          title  CDATA #REQUIRED
          width  CDATA #IMPLIED
          height CDATA #IMPLIED>

<!ELEMENT series EMPTY>
<!ATTLIST series
		  name        CDATA #REQUIRED
          cursor      CDATA #REQUIRED
          separateby  CDATA #IMPLIED
          aggregateby CDATA #IMPLIED
          aggfunc     CDATA "average"
          lowerlimit  CDATA #IMPLIED
          upperlimit  CDATA #IMPLIED
          mode        CDATA #IMPLIED
          sampleunit  CDATA "1s">
<!-- Internal DTF Elements -->
<!-- add elements as necessary to get more information out of the 
     toString on the Action classes -->

<!ELEMENT nodeinfo EMPTY>
<!ATTLIST nodeinfo 
          id   		CDATA #REQUIRED>

<!ELEMENT lock EMPTY>
<!ATTLIST lock 
          id   		CDATA #REQUIRED>

<!ELEMENT unlock EMPTY>
<!ATTLIST unlock 
          id    CDATA #REQUIRED
          owner CDATA #IMPLIED>
          
<!ELEMENT connect EMPTY>
<!ATTLIST connect
          id    CDATA #REQUIRED>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/hc_corruption_detection.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="hc_corruption_detection">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>
        Honeycomb corruption detection test, uses the CorruptingWritableChannel 
        to corrupt the stream being returned from honeycomb to test the 
        VerifyWritableChannel code.
        </description>
    </info>
    
    <local>
        <createstorage id="INPUT"  path="${dtf.xml.path}/input"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>
      
      	<loadproperties uri="storage://INPUT/hc.properties"/> 
      	<import uri="storage://INPUT/${hc.metadata.filename}"/>
    </local>
    
	<local>
        <lockcomponent id="CLIENT1">
        	<attrib name="hc.client.type" value="${hc.client.type}"/>
        </lockcomponent>
	</local>

	<for property="filetype" range="deadbeef,random">
    	<for property="filesize" range="0,1024,9999,99999,1048576">
        	<local>
    	      	<property name="offset" value="${dtf.timestamp}" overwrite="true"/>
        		<echo>Storing file
                              length:  ${filesize} byte(s)
                              offset:  ${offset} byte(s)
                              type:    ${filetype}</echo>
        	</local>
        	<record type="object" 
        	        event="hc"
        		    uri="property://object">
        			<component id="CLIENT1">
        				<store datavip="${hc.cluster.datavip}"
        					   port="${hc.cluster.dataport}">
        					<file length="${filesize}" 
        					      type="${filetype}"
        					      offset="${offset}"/>
        				</store>
        			</component>
        	</record>
        	
        	<local>
        		<echo>Retrieving file (generating corruption on client side)
                              oid:     ${object.oid}
                              length:  ${filesize} byte(s)
                              offset:  ${offset} byte(s)
                              type:    ${filetype}</echo>
        	</local>
        	<try>
            	<component id="CLIENT1">
            		<retrieve datavip="${hc.cluster.datavip}"
            			      port="${hc.cluster.dataport}"
            			      oid="${object.oid}"
            			      verify="true"
            			      corrupt="true">
            			<file length="${filesize}" 
            			      type="${filetype}"
            			      offset="${offset}"/>
            		</retrieve>
            	</component>
        		<catch exception="${dtf.DTFException}" property="message">
        			<local>
        				<echo>Correctly detected corruption on retrieve: ${message}</echo>
        			</local>
        		</catch>
        	</try>
        	
        	<local>
        		<echo>Retrieving file (using wrong offset on file verification)
                              oid:     ${object.oid}
                              length:  ${filesize} byte(s)
                              offset:  ${offset} byte(s)
                              type:    ${filetype}</echo>
        	</local>
        	<try>
            	<component id="CLIENT1">
            		<retrieve datavip="${hc.cluster.datavip}"
            			      port="${hc.cluster.dataport}"
            			      oid="${object.oid}"
            			      verify="true"
            			      corrupt="true">
            			<file length="${filesize}" 
            			      type="${filetype}"
            			      offset="3939393"/>
            		</retrieve>
            	</component>
        		<catch exception="${dtf.DTFException}" property="message">
        			<local>
        				<echo>Correctly detected corruption on retrieve: ${message}</echo>
        			</local>
        		</catch>
        	</try>
            
            
        	<local>
        		<echo>Retrieving file 
                              oid:     ${object.oid}
                              length:  ${filesize} byte(s)
                              offset:  ${offset} byte(s)
                              type:    ${filetype}</echo>
        	</local>
        	<component id="CLIENT1">
        		<retrieve datavip="${hc.cluster.datavip}"
        			      port="${hc.cluster.dataport}"
        			      oid="${object.oid}"
        			      verify="true">
        			<file length="${filesize}" 
        			      type="${filetype}"
        			      offset="${offset}"/>
        		</retrieve>
        	</component>
        </for>
	</for>
</script>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/graph.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="graph">
	<info>
		<author>
			<name>Rodney Gomes</name>
			<email>rodney.gomes@sun.com</email>
		</author>
		<description>
        Analyze and create graphs of the results of Honeycomb performance tests.</description>
	</info>

	<local>
		<createstorage id="INPUT" path="${dtf.xml.path}/input" />
		<createstorage id="OUTPUT" path="${dtf.xml.path}/output" />

	    <loadproperties uri="storage://INPUT/hc.properties"/> 
        
        <property name="runid" value="notset"/>
	</local>

    <function name="graphOpsPerSecond">
        <param name="operation.name" type="required"/>
        <param name="operation.event" type="required"/>
        <param name="operation.field" type="required"/>
        <param name="operation.units" type="required"/>
        
        <param name="filesize" type="required"/>
        <param name="client.stats.uri" type="required"/>
        <param name="output" type="required"/>
       
        <if>
            <eq op1="${runid}" op2="notset"/>
            <then>
                <query uri="${client.stats.uri}"
                       type="txt"
                       event="${operation.event}"
                       cursor="cscursor">
                    <select>
                        <field name="${operation.field}"/>
                        <field name="client"/>
                    </select>
                    <where>
                        <eq op1="succeeded" op2="true"/>
                    </where>
                </query> 
            </then>
            <else>
                <query uri="${client.stats.uri}"
                       type="txt"
                       event="${operation.event}"
                       cursor="cscursor">
                    <select>
                        <field name="${operation.field}"/>
                        <field name="client"/>
                    </select>
                    <where>
                        <and>
                            <eq op1="succeeded" op2="true"/>
                            <eq op1="runid" op2="${runid}"/>
                        </and>
                    </where>
                </query> 
            </else>
        </if>
        
        <if>
            <eq op1="${operation.name}" op2="query"/>
            <then>
                <local>
                    <property name="title" value="${md.type} ${operation.name}"/>
                </local>
            </then>
            <else>
                <local>
                    <property name="title" value="${operation.name} ${filesize} byte objects."/>
                </local>
            </else> 
        </if>
       
        <graph uri="${output}" type="${hc.graph.type}" title="${title}">
            <series name="${operation.name} ${operation.units}"
                    cursor="cscursor" 
                    mode="histogram"
                    sampleunit="1s"/> 
        </graph>
    </function>
    
    <function name="graphBytesPerSecond">
        <param name="operation.name" type="required"/>
        <param name="operation.event" type="required"/>
        <param name="operation.field" type="required"/>
        <param name="operation.units" type="required"/>
        
        <param name="filesize" type="required"/>
        <param name="client.stats.uri" type="required"/>
        <param name="output" type="required"/>
       
        <if>
            <eq op1="${runid}" op2="notset"/>
            <then>
                <query uri="${client.stats.uri}"
                       type="txt"
                       event="${operation.event}"
                       cursor="cscursor">
                    <select>
                        <field name="${operation.field}"/>
                        <field name="client"/>
                    </select>
                    <where>
                        <eq op1="succeeded" op2="true"/>
                    </where>
                </query> 
            </then>
            <else>
                <query uri="${client.stats.uri}"
                       type="txt"
                       event="${operation.event}"
                       cursor="cscursor">
                    <select>
                        <field name="${operation.field}"/>
                        <field name="client"/>
                    </select>
                    <where>
                        <and>
                            <eq op1="succeeded" op2="true"/>
                            <eq op1="runid" op2="${runid}"/>
                        </and>
                    </where>
                </query> 
            </else>
        </if>
        
        <if>
            <eq op1="${operation.name}" op2="query"/>
            <then>
                <local>
                    <property name="title" value="${md.type} ${operation.name}"/>
                </local>
            </then>
            <else>
                <local>
                    <property name="title" value="${operation.name} ${filesize} byte objects."/>
                </local>
            </else> 
        </if>
            
        <graph uri="${output}" type="${hc.graph.type}" title="${title}">
            <series name="${operation.name} ${operation.units}"
                    cursor="cscursor" 
                    aggregateby="${operation.field}"
                    aggfunc="sum"
                    sampleunit="1s"/> 
        </graph>
    </function>
    
    <if>
        <eq op1="${hc.operation}" op2="query"/>
        <then>
            <local>
                <property name="field" value="results"/>
                <property name="units" value="results/sec"/>
            </local>
        </then>
    </if>
    
    <if>
        <eq op1="${hc.operation}" op2="retrievemd"/>
        <then>
            <local>
                <property name="field" value="fields"/>
                <property name="units" value="fields/sec"/>
            </local>
        </then>
    </if>
    
    <local>
        <property name="field" value="size"/>
        <property name="units" value="bytes/sec"/>
    </local>
    
    <if>
        <eq op1="${hc.storewithmd}" op2="true"/>
        <then>
            <local>
                <property name="delete.md.type" value="md"/>
            </local>
        </then>
        <else>
            <local>
                <property name="delete.md.type" value="data"/>
            </local>
        </else>
    </if>

    <if>
        <eq op1="${hc.operation}" op2="delete"/>
        <then>
            <local>
                <property name="stats.uri" 
                          value="storage://OUTPUT/${hc.operation}_${delete.md.type}_perf_${hc.filesize}.txt"/>
                <property name="output.ops" 
                          value="storage://OUTPUT/${hc.operation}_${delete.md.type}_${hc.filesize}_ops_per_second.${hc.graph.type}"/>
                <property name="output.results"
                          value="storage://OUTPUT/${hc.operation}_${delete.md.type}_${hc.filesize}_bytes_per_second.${hc.graph.type}"/>
            </local>
        </then>
    </if>
           
    <if>
        <eq op1="${hc.operation}" op2="query"/>
        <then>
            <local>
                <property name="stats.uri" 
                          value="storage://OUTPUT/${hc.operation}_${md.type}_perf.txt"/>
                <property name="output.ops" 
                          value="storage://OUTPUT/${hc.operation}_${md.type}_ops_per_second.${hc.graph.type}"/>
                <property name="output.results"
                          value="storage://OUTPUT/${hc.operation}_${md.type}_results_per_second.${hc.graph.type}"/>
            </local>
        </then>
    </if>
            
    <local>
        <property name="stats.uri" 
                  value="storage://OUTPUT/${hc.operation}_perf_${hc.filesize}.txt"/>
        <property name="output.ops" 
                  value="storage://OUTPUT/${hc.operation}_${hc.filesize}_ops_per_second.${hc.graph.type}"/>
        <property name="output.results"
                  value="storage://OUTPUT/${hc.operation}_${hc.filesize}_bytes_per_second.${hc.graph.type}"/>
    </local>
            
    <call function="graphOpsPerSecond">
        <property name="operation.name"   value="${hc.operation}"/>
        <property name="operation.event"  value="hc.${hc.operation}"/>
        <property name="operation.field"  value="${field}"/>
        <property name="operation.units"  value="ops/s"/>
                
        <property name="filesize"         value="${hc.filesize}"/>
        <property name="client.stats.uri" value="${stats.uri}"/>
        <property name="output" value="${output.ops}"/>
    </call>
                
    <call function="graphBytesPerSecond">
        <property name="operation.name"   value="${hc.operation}"/>
        <property name="operation.event"  value="hc.${hc.operation}"/>
        <property name="operation.field"  value="${field}"/>
        <property name="operation.units"  value="${units}"/>
                
        <property name="filesize"         value="${hc.filesize}"/>
        <property name="client.stats.uri" value="${stats.uri}"/>
        <property name="output" value="${output.results}"/>
    </call>
    
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/property_resolution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="property_resolution">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>DTF unit test for complex property resolution.</description>
    </info>

    <local>
        <createstorage id="INPUT"  path="${dtf.xml.path}/input" />
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output" />

        <loadproperties uri="storage://INPUT/ut.properties"/>

        <echo message="*** Property resolution unit test ***" />
    </local>

    <for property="i" range="1..10">
        <for property="j" range="1..10">
            <local>
                <property name="property${i}${j}" value="${i}-${j}"/>
            </local> 
        </for>
    </for>
   
    <for property="i" range="1..10">
        <for property="j" range="1..10">
            <if>
                <neq  op1="${property${i}${j}}" op2="${i}-${j}"/>
                <then>
                    <fail message="property mismatch for property${i}${j}: ${property${i}${j}} != ${i}-${j}"/>
                </then>
            </if>
        </for>
    </for>
    
    <for property="i" range="1..10">
        <for property="j" range="1..10">
            <local>
                <property name="a${i}b${j}c" value="${i}-${j}"/>
            </local> 
        </for>
    </for>
   
    <for property="i" range="1..10">
        <for property="j" range="1..10">
            <if>
                <neq  op1="${a${i}b${j}c}" op2="${i}-${j}"/>
                <then>
                    <fail message="property mismatch for [a${i}b${j}c]: ${a${i}b${j}c} != ${i}-${j}"/>
                </then>
            </if>
        </for>
    </for>
    

</script>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/hc_schemacheck.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="hc_devmode">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>
        Schema check test verifies that a specified schema is loaded and if not 
        makes sure to load such schema to the cluster.</description>
    </info>

    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input" />
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output" />
        <createstorage id="TINPUT" path="${dtf.xml.path}" />

        <loadproperties uri="storage://INPUT/hc.properties" />
    </local>

    <local>
        <lockcomponent id="CLUSTER" timeout="30s">
            <attrib name="hc.cluster.type" value="${hc.cluster.type}" />
        </lockcomponent>
    </local>

    <component id="CLUSTER">
        <waitforhadb/>
        <validateschema schema="${hc.metadata.schema}"/>
    </component>
    
</script>
