=== VijayEluri/honeycomb/hctest/dtf/tests/ut/dtf.dtd
<!ENTITY % aggregations "for|sequence|parallel|try|timer|distribute|parallelloop|result|if|fail|sleep|log">
<!ENTITY % functions "function|call">
<!ENTITY % events "record|event|query|nextresult|stats|graph">
<!ENTITY % components "local|component">
<!ENTITY % local_commands "loadproperties|createstorage|lockcomponent|unlockcomponent|property|import|createrange|cat">
<!ENTITY % component_commands "sleep|echo|event|fail|getfile|stopcomponent|loop|fetchresult|attribute">
<!ENTITY % test_commands "testsuite|testscript">

<!ENTITY % conditions "and|eq|gt|lt|neq|or|within">

<!ENTITY % dtf_tags "%aggregations;|%components;|%test_commands;|%events;|%functions;"> 

<!ELEMENT script ( info, (%dtf_tags;)* )>
<!ATTLIST script
          name        CDATA #REQUIRED>

<!ELEMENT info ( author,description ) >

<!ELEMENT author ( name, email )>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT function (param*,(%dtf_tags;)*)>
<!ATTLIST function
          name CDATA #REQUIRED>

<!ELEMENT param EMPTY>
<!ATTLIST param 
          name CDATA #REQUIRED
          type (optional|required) "optional">

<!ELEMENT call (property)*>
<!ATTLIST call
          function CDATA #REQUIRED>
          
<!ELEMENT import EMPTY>
<!ATTLIST import
          uri 		 CDATA #REQUIRED
          loadFuncs  CDATA "true"
          loadRefs   CDATA "true">
  
<!ELEMENT testsuite ANY>
<!ATTLIST testsuite
          name   			CDATA #REQUIRED
          continueOnFailure CDATA #IMPLIED> 

<!ELEMENT testscript (testproperty)*>
<!ATTLIST testscript
          uri  CDATA #REQUIRED>

<!ELEMENT testproperty EMPTY>
<!ATTLIST testproperty
          name  CDATA #REQUIRED
          value CDATA #REQUIRED>

<!ELEMENT timer (%dtf_tags;|%component_commands;)*>
<!ATTLIST timer
          interval CDATA #REQUIRED
          property CDATA #IMPLIED>

<!ELEMENT sequence (%dtf_tags;)*>

<!ELEMENT parallel (%dtf_tags;)*>

<!ELEMENT local (%local_commands;|%component_commands; | attribute)*>

<!ELEMENT component (%component_commands; | event | attribute)*>
<!ATTLIST component
          id        CDATA #REQUIRED>

<!ELEMENT loadproperties EMPTY>
<!ATTLIST loadproperties
          uri          CDATA #REQUIRED
          overwrite    CDATA #IMPLIED>

<!ELEMENT cat (#PCDATA)>
<!ATTLIST cat
          uri     CDATA #REQUIRED
          append  CDATA "true"
          trim    CDATA "true">
          
<!ELEMENT log (#PCDATA)>
<!ATTLIST log 
          tag   CDATA "log"
          level CDATA "info">
          
<!ELEMENT echo (#PCDATA)>
<!ATTLIST echo
          message CDATA #IMPLIED>

<!ELEMENT lockcomponent (attrib)*>
<!ATTLIST lockcomponent
          id      CDATA #REQUIRED
          name    CDATA #IMPLIED
          timeout CDATA "60s">

<!ELEMENT attrib EMPTY>
<!ATTLIST attrib
          name  CDATA #IMPLIED
          value CDATA #IMPLIED>

<!ELEMENT unlockcomponent EMPTY>
<!ATTLIST unlockcomponent 
          id CDATA #REQUIRED>

<!ELEMENT stopcomponent EMPTY>

<!ELEMENT createstorage EMPTY>
<!ATTLIST createstorage
          id   CDATA #REQUIRED
          path CDATA #REQUIRED>
          
<!ELEMENT createrange EMPTY>
<!ATTLIST createrange
          name    CDATA #REQUIRED
          value   CDATA #REQUIRED
          recycle CDATA #IMPLIED>
          
<!-- moving files to/from components tags -->

<!ELEMENT putfile EMPTY>
<!ATTLIST putfile
		  uri        CDATA #REQUIRED
		  remotefile CDATA #REQUIRED>

<!ELEMENT getfile EMPTY>
<!ATTLIST getfile
		  uri        CDATA #REQUIRED
		  remotefile CDATA #REQUIRED>

<!-- flow control tags -->
          
<!ELEMENT try ((%dtf_tags;),catch*,finally?)>
<!ELEMENT catch (%dtf_tags;)>
<!ATTLIST catch
          exception CDATA #IMPLIED
          property  CDATA #IMPLIED>
<!ELEMENT finally (%dtf_tags;)>

<!ELEMENT fail EMPTY>
<!ATTLIST fail
          message    CDATA #REQUIRED>

<!ELEMENT for (%dtf_tags;)*>
<!ATTLIST for 
          property CDATA #REQUIRED
          range    CDATA #REQUIRED>

<!ELEMENT distribute (%dtf_tags;)>
<!ATTLIST distribute
          func 			CDATA #IMPLIED
          duration 		CDATA #IMPLIED
          iterations 	CDATA #IMPLIED
          timer 		CDATA #IMPLIED
          unit 			CDATA "1s"
          property 		CDATA #IMPLIED
          workers 		CDATA #REQUIRED
          id            CDATA #IMPLIED>

<!ELEMENT parallelloop (%dtf_tags;)>
<!ATTLIST parallelloop
          range CDATA #IMPLIED
          property CDATA #IMPLIED>

<!ELEMENT loop (loop|%component_commands;)*>
<!ATTLIST loop
          range 	CDATA #IMPLIED
          property 	CDATA #IMPLIED
          type		CDATA "sequence">

<!ELEMENT fetchresult EMPTY>
<!ATTLIST fetchresult
          cursor    CDATA #REQUIRED
          recycle   CDATA #IMPLIED
          fetchsize CDATA #IMPLIED>
          
<!ELEMENT sleep EMPTY>
<!ATTLIST sleep 
          time CDATA #REQUIRED>

<!ELEMENT result ANY>
<!ATTLIST result
          uri    CDATA	#IMPLIED
          type   CDATA	"xml">

<!ELEMENT record (attribute*,(%dtf_tags;)*)>
<!ATTLIST record
          uri    CDATA #IMPLIED
          type   CDATA #REQUIRED
          event  CDATA #IMPLIED
          append CDATA #IMPLIED
          refid  CDATA #IMPLIED>

<!ELEMENT event ANY>
<!ATTLIST event 
          name  CDATA #IMPLIED
          id    CDATA #IMPLIED
          refid CDATA #IMPLIED>
          
<!ELEMENT stats  EMPTY>
<!ATTLIST stats 
          cursor CDATA #REQUIRED
          event  CDATA #REQUIRED>

<!ELEMENT property EMPTY>
<!ATTLIST property
          name      CDATA #REQUIRED
          value     CDATA #REQUIRED
          overwrite CDATA #IMPLIED>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
          name  CDATA #REQUIRED
          value CDATA #REQUIRED
          type  CDATA "string"
          index CDATA #IMPLIED
          length CDATA "64">

<!ELEMENT nextresult EMPTY>
<!ATTLIST nextresult
          cursor  CDATA #REQUIRED
          recycle CDATA #IMPLIED>

<!ELEMENT query (select?,where?) >
<!ATTLIST query 
          uri    CDATA	#REQUIRED
          type   CDATA  "database"
          event  CDATA  #REQUIRED
          cursor CDATA 	#REQUIRED> 

<!ELEMENT select (field)*>

<!ELEMENT field EMPTY>
<!ATTLIST field 
          name CDATA #REQUIRED
          type CDATA #IMPLIED>

<!ELEMENT where (%conditions;)>

<!ELEMENT and (%conditions;)*>
<!ELEMENT or (%conditions;)*>

<!ELEMENT gt EMPTY>
<!ATTLIST gt 
          op1	    CDATA #REQUIRED
          op2		CDATA #REQUIRED
          type  	CDATA "string"
          nullable  CDATA "false">

<!ELEMENT lt EMPTY>
<!ATTLIST lt 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">

<!ELEMENT eq EMPTY>
<!ATTLIST eq 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">

<!ELEMENT neq EMPTY>
<!ATTLIST neq 
          op1      CDATA #REQUIRED
          op2      CDATA #REQUIRED
          type     CDATA "string"
          nullable CDATA "false">
          
<!ELEMENT within EMPTY>
<!ATTLIST within
          op1       CDATA #REQUIRED
          op2       CDATA #REQUIRED
          tolerance CDATA #REQUIRED>

<!ELEMENT if ((%conditions;),then,else?) >

<!ELEMENT then (%dtf_tags;)* >
<!ELEMENT else (%dtf_tags;)* >

<!ELEMENT graph (series)*>
<!ATTLIST graph
          uri    CDATA #IMPLIED
          type   CDATA #REQUIRED
          title  CDATA #REQUIRED
          width  CDATA #IMPLIED
          height CDATA #IMPLIED>

<!ELEMENT series EMPTY>
<!ATTLIST series
		  name        CDATA #REQUIRED
          cursor      CDATA #REQUIRED
          separateby  CDATA #IMPLIED
          aggregateby CDATA #IMPLIED
          aggfunc     CDATA "average"
          lowerlimit  CDATA #IMPLIED
          upperlimit  CDATA #IMPLIED
          mode        CDATA #IMPLIED
          sampleunit  CDATA "1s">
<!-- Internal DTF Elements -->
<!-- add elements as necessary to get more information out of the 
     toString on the Action classes -->

<!ELEMENT nodeinfo EMPTY>
<!ATTLIST nodeinfo 
          id   		CDATA #REQUIRED>

<!ELEMENT lock EMPTY>
<!ATTLIST lock 
          id   		CDATA #REQUIRED>

<!ELEMENT unlock EMPTY>
<!ATTLIST unlock 
          id    CDATA #REQUIRED
          owner CDATA #IMPLIED>
          
<!ELEMENT connect EMPTY>
<!ATTLIST connect
          id    CDATA #REQUIRED>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/analyze.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="perfmonitor">
	<info>
		<author>
			<name>Rodney Gomes</name>
			<email>rodney.gomes@sun.com</email>
		</author>
		<description></description>
	</info>

	<local>
		<createstorage id="INPUT" path="${dtf.xml.path}/input" />
		<createstorage id="TINPUT" path="${dtf.xml.path}" />
		<createstorage id="OUTPUT" path="${dtf.xml.path}/output" />

		<loadproperties uri="storage://INPUT/hc.properties" />
		<import uri="storage://INPUT/${hc.metadata.filename}" />

		<property name="hc.test.db.type" value="txt" />
		<property name="hc.iteration.duration" value="60s" />
	</local>

	<query uri="storage://INPUT/clientsidestats.log" type="txt"
		event="hc.store" cursor="perfcursor" />

	<record type="object" uri="property://dbperf">
		<stats cursor="perfcursor" event="stats" />
	</record>
	<local>
		<echo>
			Events per second: ${dbperf.avg_occ} 
			Total of Events:   ${dbperf.tot_occ} 
			Total Duration:    ${dbperf.tot_dur}s
		</echo>
	</local>

	<query uri="storage://INPUT/serversidestats.log" 
	       type="txt"
	       event="hc.stat.cpu" 
	       cursor="sscursor"/>

	<query uri="storage://INPUT/clientsidestats.log" 
	       type="txt"
	       event="hc.store"
	       cursor="cscursor">
		<select>
			<field name="commitlatency" />
		</select>
	</query>

	<query uri="storage://INPUT/clientsidestats.log" 
	       type="txt"
	       event="hc.store"
	       cursor="cscursor2">
		<select>
			<field name="ctime" />
		</select>
	</query>
	
	<graph uri="storage://OUTPUT/graph.svg"
     	   type="${hc.graph.type}"
     	   title="CPU Usage With Store Operations">
     	   
     	<series name="Commit Latency (ms)"
			cursor="cscursor"/>

     	<series name="Stores per second"
			cursor="cscursor2" 
			mode="histogram"
		    sampleunit="1s"/> 
			
		<series name="Average CPU Usage across the cluster (%)" 
		        cursor="sscursor"
			    aggregateby="node"
			    sampleunit="5s"/>
	</graph>

	<query uri="storage://INPUT/serversidestats.log" 
	       type="txt"
	       event="hc.stat.cpu" 
	       cursor="sscursor2">
	       <select>
	       		<field name="API-SERVERS"/>
	       		<field name="node"/>
	       </select>
	</query>

	<graph uri="storage://OUTPUT/hadb_cpu_usage.svg"
     	   type="${hc.graph.type}"
     	   title="API-SERVERS CPU usage on all nodes">
		<series name="CPU Usage (%)" 
		        cursor="sscursor2"
		        separateby="node"/>
	</graph>

</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="component">
    <info>
         <author>
             <name>Rodney Gomes</name>
             <email>rodney.gomes@sun.com</email>
         </author> 
         <description>
             Test the basic functionality of the component tag which is used to
             execute remote tasks on remote components in the DTF architecture.
         </description>
    </info>
    
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        <loadproperties uri="storage://INPUT/ut.properties"/>
    </local>
	
    <for property="iteration" range="[0..20]">
        <sequence>
            <local>
                <echo>Iteration ${iteration}: Locking and Unlocking one DTFA</echo>
                <lockcomponent id="DTFA1" timeout="10s">
                	<attrib name="type" value="DTFA"/>
                </lockcomponent>
                <unlockcomponent id="DTFA1"/>
            </local>
        </sequence>
    </for>
    
    <try>
        <sequence>
            <local>
                <echo>About to lock a dtfa by name and this will fail.</echo>
                <lockcomponent id="DTFA2" timeout="0">
                	<attrib name="type" value="DTFA"/>
                	<attrib name="name" value="INEXISTENT"/>
                </lockcomponent>
                <fail message="The previous lockcomponent should have failed."/>
            </local>
        </sequence>
        <catch exception="${dtf.LockException}">
            <sequence>
                <local>
                    <echo>Caught the exception correctly</echo>
                </local>
            </sequence>
        </catch>
    </try>
    
    <local>
        <lockcomponent id="DTFA1">
        	<attrib name="type" value="DTFA"/>
        </lockcomponent>
       
        <echo>Remotely executing an echo on the locked agent DTFA1</echo>
    </local>
    
    <component id="DTFA1">
        <echo>***********************************</echo>
        <echo>This is being printed from the dtfx</echo>
        <echo>***********************************</echo>
    </component>
    
    <component id="DTFA1">
        <echo>********************************************</echo>
        <echo>Echo property on component: ${dtf.node.name}</echo>
        <echo>********************************************</echo>
    </component>
    
</script>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/retrieve.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="retrieve">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>Honeycomb retrieve test.</description>
    </info>
        
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>
        
        <loadproperties uri="storage://INPUT/hc.properties"/>
		<!-- default values incase you want to run this test on its own
		     instead of within the perf tessuite -->
		<property name="runid" value="${dtf.timestamp}"/>
        <metadata id="MDEMPTY"/>
    </local>
    
    <!-- Lock as many components as necessary by the test. -->
    <for property="client" range="1..${hc.perf.clients}">
        <local>
            <lockcomponent id="CLIENT${client}">
                <attrib name="hc.client.type" value="${hc.client.type}"/>
            </lockcomponent>
        </local>
    </for>
    
    <!-- select oids from object database where we've already had stores -->
    <query type="${hc.test.db.type}" 
           event="hc.object" 
           uri="storage://OUTPUT/${hc.test.db.file}"
           cursor="object">
        <select>
            <field name="oid"/>
            <field name="file.type"/>
            <field name="file.length"/>
            <field name="file.offset"/>
        </select>
        <where>
            <and>
                <neq op1="deleted"      op2="true" nullable="true"/>
                <eq  op1="file.length"  op2="${hc.filesize}"/>
            </and>
        </where>
    </query>
    
    <local>
        <echo>
        Retrieving ${hc.filesize} byte(s) objects 
        from ${hc.cluster.datavip}:${hc.cluster.dataport} 
        using ${hc.perf.clients} client(s) and ${hc.perf.threads} thread(s)
        for ${hc.perf.duration}</echo>
    </local>

    <try>
        <record type="txt"
                event="hc.retrieve" 
                uri="storage://OUTPUT/retrieve_perf_${hc.filesize}.txt">
        	<attribute name="runid" value="${runid}"/>
            <parallelloop property="client" range="1..${hc.perf.clients}">
			    <component id="CLIENT${client}">
                    <attribute name="client" value="CLIENT${client}"/>
                    <loop range="1..${hc.perf.threads}"
                          property="thread"
                          type="parallel"> 
                		<loop range="${hc.perf.duration}" 
                              property="iteration"
                              type="timer">
     				        <fetchresult cursor="object" recycle="true"/>
                            <retrieve datavip="${hc.cluster.datavip}"
                                      port="${hc.cluster.dataport}" 
                                      oid="${object.oid}"
                                      node="${hc.loadgaming.node}"
                                      verify="${hc.data.verify}"
            					      monitor="${hc.channel.monitoring}"
                                      continueOnFailure="${hc.continueonfailure}">
                            	<file length="${object.file.length}"
                            	      type="${object.file.type}"
                            	      offset="${object.file.offset}"/>
                            </retrieve>
                        </loop>
                    </loop>
                </component>
            </parallelloop>
        </record>
    	<catch exception="${dtf.NoMoreResultsException}">
        	<local>
                <echo>All done retrieving, no more data to delete.</echo>
            </local>
        </catch>
    </try>
    <local>
        <echo>
        Runid: ${runid}</echo>
    </local>
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/ut/util.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="util">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>Unit test utility functions.</description>
    </info>
   
    <function name="checkRecordCount">
    	<param name="recorder.location" type="required"/>
    	<param name="recorder.type" type="required"/>
    	<param name="record.count" type="required"/>
    	<param name="event.name" type="required"/>
    	
        <query uri="${recorder.location}"
               type="${recorder.type}" 
               cursor="cursor1" 
               event="${event.name}"/>
               
       	<try> 
            <sequence>
              	<nextresult cursor="cursor1"/>
                <for property="i" range="1..1000">
                	<nextresult cursor="cursor1"/>
                </for>
            </sequence>
            <catch exception="${dtf.NoMoreResultsException}">
       			<if>
       				<neq op1="${i}" op2="${record.count}"/>
       				<then>
       					<local>
       						<fail message="Did not just get back the expected ${record.count} elements, got ${i} elements."/>
       					</local>
       				</then>
       				<else>
       					<local>
       						<echo>Counted ${record.count} elements correctly.</echo>
       					</local>
       				</else>	
       			</if>	
            </catch>
        </try>
    </function>
    
</script>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/perfmonitor.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="perfmonitor">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>
        </description>
    </info>
    
    <local>
        <createstorage id="INPUT"  path="${dtf.xml.path}/input"/>
        <createstorage id="TINPUT"  path="${dtf.xml.path}"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>

      	<loadproperties uri="storage://INPUT/hc.properties"/> 
      	<import uri="storage://INPUT/${hc.metadata.filename}"/>
      	
      	<property name="hc.test.db.type" value="txt"/>
      	<property name="hc.iteration.duration" value="60s"/>
    </local>
    
	<local>
        <lockcomponent id="CLUSTER">
        	<attrib name="hc.cluster.type" value="${hc.cluster.type}"/>
        </lockcomponent>
	</local>

	<component id="CLUSTER">
		<perfmonitor command="start" sample="1"/>	
	</component>

	<for property="client" range="${hc.client.ids}">
    	<local>
            <lockcomponent id="${client}">
            	<attrib name="type" value="${hc.client.type}"/>
            </lockcomponent>
    	</local>
    </for>
    
	<local>
		<echo>Storing ${hc.filesize} byte files 
		      to ${hc.cluster.datavip}:${hc.cluster.dataport} 
		      for ${hc.iteration.duration}</echo>
	</local>
	<record type="txt"
	        event="hc"
		    uri="storage://OUTPUT/clientsidestats.log"
		    append="false">
  			<parallelloop property="client" range="${hc.client.ids}">
        		<timer interval="${hc.iteration.duration}">
        			<component id="${client}">
        				<store datavip="${hc.cluster.datavip}"
        					   port="${hc.cluster.dataport}"
        					   continueOnFailure="${hc.onfailure}"
        					   monitor="${hc.channel.monitoring}">
        					<file length="${hc.filesize}" 
        					      type="${hc.filetype}"/>
        					<metadata refid="MDREF"/>
        				</store>
        			</component>
        		</timer>
       		</parallelloop>
	</record>
	
	<component id="CLUSTER">
		<perfmonitor command="stop"/>	
		<perfmonitor command="collectlogs" 
		             uri="storage://OUTPUT/serversidestats.log"/>	
	</component>


	<query uri="storage://INPUT/serversidestats.log" 
           type="txt" 
           event="hc.stat.mem"
           cursor="sscursor">
           <where>
           		<or>
	           		<eq op1="node" op2="hcb101"/>
           		</or>
           </where>
    </query>
    
    <query uri="storage://INPUT/clientsidestats.log" 
           type="txt" 
           event="hc.store"
           cursor="cscursor">
           <select>
          		<field name="commitlatency"/> 
           </select>
    </query>
           
	<graph uri="storage://OUTPUT/graph.svg"
	       type="svg"
	       title="CPU Usage With Store Operations">
	       
    	<series name="Store Commit Latency (ms)" 
    	        cursor="cscursor" mode="histogram"/>
    	        
		<series name="Node1 CPU Usage (%)" 
		        cursor="sscursor"
		        lowerlimit="0.0"
		        upperlimit="100.0"/>
	</graph>	
	
</script>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/hc_object_lifecycle.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="hc_object_lifecycle">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>
        Honeycomb Object LifeCycle test is very simple and tries to simluate the
        life of an object in honeycomb. So the object is created, later 
        retrieved we might retrieve its metadata then followed by adding some 
        more metadata verify that all of the oids created can still get you your 
        metadata and your data. Then honeycomb query API is used to verify that
        the object can be found through query. Then later one of the metadata 
        references are deleted and verified to be actually deleted. Finally the 
        last reference is deleted and this objects life has come to an end in 
        the system.
        </description>
    </info>
    
    <local>
        <createstorage id="INPUT"  path="${dtf.xml.path}/input"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>

      	<loadproperties uri="storage://INPUT/hc.properties"/> 
      	<import uri="storage://INPUT/${hc.metadata.filename}"/>
    </local>
    
	<local>
        <lockcomponent id="CLIENT1">
        	<attrib name="hc.client.type" value="${hc.client.type}"/>
        </lockcomponent>

        <lockcomponent id="CLUSTER">
        	<attrib name="hc.cluster.type" value="${hc.cluster.type}"/>
        </lockcomponent>
	</local>
	
	<function name="retrieveObject">
		<param name="oid" type="required"/>
		<local>
			<echo>Retrieving data for ${oid} with verification</echo>
		</local>
    	<component id="CLIENT1">
    		<retrieve datavip="${hc.cluster.datavip}"
    			      port="${hc.cluster.dataport}"
    			      oid="${oid}"
    			      verify="true">
    			<file length="${hc.filesize}" 
    			      type="${object.file.type}"/>
    		</retrieve>
    	</component>
	</function>
	
	<function name="retrieveMetadata">
		<param name="oid" type="required"/>
		<local>
			<echo>Retrieving metadata for ${oid} with verification</echo>
		</local>
    	<component id="CLIENT1">
    		<retrievemd datavip="${hc.cluster.datavip}"
    			        port="${hc.cluster.dataport}"
    			        oid="${oid}"
    			        verify="false">
    			<metadata refid="MDCMP"/>
    		</retrievemd>
    	</component>
	</function>

	<local>
		<echo>Storing ${hc.filesize} byte file</echo>
	</local>
	<record type="object" 
	        event="hc"
		    uri="property://object">
			<component id="CLIENT1">
				<store datavip="${hc.cluster.datavip}"
					   port="${hc.cluster.dataport}">
					<file length="${hc.filesize}" 
					      type="${hc.filetype}"/>
					<metadata refid="MDREF"/>
				</store>
			</component>
	</record>
    
	<call function="retrieveObject">
		<property name="oid" value="${object.oid}"/>
	</call>
    
	<call function="retrieveMetadata">
		<property name="oid" value="${object.oid}"/>
	</call>
	
	<local>
		<echo>Adding metadata for ${object.oid}</echo>
	</local>
	<record type="object" 
	        event="hc"
		    uri="property://object2">
    	<component id="CLIENT1">
    		<addmetadata datavip="${hc.cluster.datavip}"
    			         port="${hc.cluster.dataport}"
    			         oid="${object.oid}">
    			<metadata refid="MDREF"/>
    		</addmetadata>
    	</component>
	</record>
	
	<local>
		<echo>Query for the metadata relevant to both previous metadata objects.</echo>
	</local>

	<!--  I think that here is where I should introduce the notion of 
	      querying honeycomb in the same manner we'd query the recorder results
	      database and allow for more control over what is being queried-->	
<!-- <record type="object" 
	        event="hc"
		    uri="property://queryresult">
      	<component id="CLIENT1">
    		<hcquery datavip="${hc.cluster.datavip}"
        	         port="${hc.cluster.dataport}">
    		</hcquery>
    	</component> 			      
    </record> -->
   
   <!-- @todo: how to verify the oids returned are the expected? --> 
	
	<call function="retrieveMetadata">
		<property name="oid" value="${object2.oid}"/>
	</call>
	
	<call function="retrieveObject">
		<property name="oid" value="${object2.oid}"/>
	</call>
	
	<local>
		<echo>Deleting ${object.oid}</echo>
	</local>
	<component id="CLIENT1">
		<delete datavip="${hc.cluster.datavip}"
			    port="${hc.cluster.dataport}"
			    oid="${object.oid}"/>
	</component>
	
</script>

=== VijayEluri/honeycomb/hctest/dtf/tests/perf/perf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">
<script name="perf">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>DTF performance testsuite.</description>
    </info>
       
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}"/>
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output"/>
    </local>
    
    <record uri="storage://OUTPUT/dtf.internals.txt" type="txt" event="dtf.perf.*">
    	<testsuite name="perfsuite">
        	<testscript uri="storage://INPUT/distribute.xml"/> 
        	<testscript uri="storage://INPUT/component.xml"/> 
    	</testsuite>
    </record>
    
</script>

=== VijayEluri/honeycomb/hctest/hc-dtf/tests/df.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE script PUBLIC "-//DTF/DTF XML Script V1.0//EN" "dtf.dtd">

<script name="df">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rodney.gomes@sun.com</email>
        </author>
        <description>Simple test to validate that the df tag does what we are 
                     expecting it to do.</description>
    </info>

    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input" />
        <createstorage id="OUTPUT" path="${dtf.xml.path}/output" />
        <createstorage id="FRAGOUTPUT" path="${dtf.xml.path}/output/frags-${dtf.timestamp}" />
        <createstorage id="TINPUT" path="${dtf.xml.path}" />

        <loadproperties uri="storage://INPUT/hc.properties" />
    </local>

    <local>
        <lockcomponent id="CLUSTER" timeout="${hc.lockcomponent.timeout}">
            <attrib name="hc.cluster.type" value="${hc.cluster.type}" />
        </lockcomponent>
    </local>

    <record type="object" uri="property://df">
        <component id="CLUSTER">
            <cli>
                <df/> 
            </cli>
        </component>
    </record>
    
    <log tag="DF">DF Output</log>
    <log tag="DF">---------</log>
    <log tag="DF">Total Space(KB):     ${df.total.kbytes}</log>
    <log tag="DF">Available Space(KB): ${df.available.kbytes}</log>
    <log tag="DF">Used Space(KB):      ${df.available.kbytes}</log>
    <log tag="DF">Usage(%):            ${df.usage.percentage}</log>
    
</script>
